# Generated by Django 5.0.6 on 2024-05-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_webapp', '0004_user_alter_product_image_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='djangoproject/static/images'),
        ),
    ]
