# Generated by Django 5.0.6 on 2024-05-25 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_webapp", "0005_product_discount_alter_product_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
