# Generated by Django 5.0.6 on 2024-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_webapp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('laptop', 'Ноутбук'), ('phone', 'Телефон'), ('headphones', 'Навушники'), ('accessories', 'Аксесуари')], default='phone', max_length=20),
        ),
    ]
